version: '3.8'

services:
  library-admin:
    build: .
    container_name: library-admin
    restart: unless-stopped
    environment:
      # Domain (required for API URL)
      - DOMAIN=${DOMAIN:-lib.ptcau.com}

      # Database connection
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-library_bot}
      - DB_USER=${DB_USER:-library_user}
      - DB_PASSWORD=${DB_PASSWORD}

      # Evolution API
      - EVOLUTION_API_URL=${EVOLUTION_API_URL:-https://api.ptcau.com}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE=${EVOLUTION_INSTANCE:-ptc}

      # Admin credentials
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}

      # App configuration
      - TIMEZONE=${TIMEZONE:-Asia/Kolkata}

    networks:
      - dokploy-network

    labels:
      - "traefik.enable=true"
      # Backend (WebSocket & API) - higher priority
      - "traefik.http.routers.library-admin-api.rule=Host(`${DOMAIN}`) && (PathPrefix(`/_event`) || PathPrefix(`/api`))"
      - "traefik.http.routers.library-admin-api.entrypoints=websecure"
      - "traefik.http.routers.library-admin-api.tls=true"
      - "traefik.http.routers.library-admin-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.library-admin-api.priority=100"
      - "traefik.http.services.library-admin-api.loadbalancer.server.port=8000"
      # Frontend (static files) - lower priority
      - "traefik.http.routers.library-admin-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.library-admin-web.entrypoints=websecure"
      - "traefik.http.routers.library-admin-web.tls=true"
      - "traefik.http.routers.library-admin-web.tls.certresolver=letsencrypt"
      - "traefik.http.routers.library-admin-web.priority=1"
      - "traefik.http.services.library-admin-web.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
